### ISSUE TITLE
图片不显示

### ISSUE THREAD

**Issue by lizhongze123** [yaozs/ImageShowPicker#3]
你好，运行程序后，图片都不显示的。换了Picasso和换了图片url，还是不能显示。

**Comment by yaozs** [comment]
请问您描述下手机版本，使用的就是这个项目直接下载的demo吗

**Comment by lizhongze123** [comment]
手机是华为荣耀，型号是CHE-TL00H,android版本是5.0.2，用的就是这里下载的demo

**Comment by yaozs** [comment]
能不能留个qq，我加你下，远程看下问题，我这没有找到问题

**Comment by lizhongze123** [comment]
好，万分感谢 793223793
