### ISSUE TITLE
“有点问题”

### ISSUE THREAD

**Issue by dongjielitianjiao** [yaozs/ImageShowPicker#7]

**Comment by dongjielitianjiao** [comment]
“相册选取的图片 回显有问题啊”，，，能否控制 占位按钮的显示与隐藏啊

**Comment by yaozs** [comment]
我这个只是一个demo，相册选取是其他选择框架的东西，可能是我没设置，你也可以用其他框架，比如takephoto，我这都是兼容的

**Comment by dongjielitianjiao** [comment]
主要是我要拿本地视频和图片。。我看你代码里面不是以ImageView为item. 我不能设置        android:scaleType=""，导致拿回来展示的UI有点辣眼睛哦.。。所以问下你哈。。。。另外关于控制占位按钮的显示与隐藏这个可以添加一个功能啊，你的只能在代码中设置 最大展示数量然后隐藏.。。。.我主要是遇上这个需求了，，，选完1个视频，则不能再次进行选择。。。。。只能默默的做逻辑判断哦。。

**Comment by yaozs** [comment]
在图片加载处理那个load类里，你可以创建你 想要实现的view比如imageview，你可以在代码中设置加载方式，关于显示隐藏这个功能，你需要这样操作，如果选择的是视频，返回后重新设置最大显示数量，并且调用show方法，这样就走通逻辑了，因为那个占位图的显示必须基于数量判断 @dongjielitianjiao

**Comment by dongjielitianjiao** [comment]
一早过来就解决了这2个问题。谢谢咯。。。万分感谢....................... @yaozs
